### ISSUE TITLE
Could not install phantomas==0.2 via pip

### ISSUE THREAD

**Issue by wladekb** [macbre/phantomas-python#5]
0.1 installs successfully.

```
wladek@wladek-pc:~/dev/sparrow$ sudo pip install phantomas
Downloading/unpacking phantomas
  Downloading phantomas-0.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/phantomas/setup.py) egg_info for package phantomas
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/phantomas/setup.py", line 6, in <module>
        with open('README.rst', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/phantomas/setup.py", line 6, in <module>

    with open('README.rst', 'r') as f:

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Cleaning up...
```

**Comment by macbre** [comment]
v0.2.1 uploaded to pypi repo

```
Successfully installed phantomas coverage pytest pylint py logilab-common astroid six
```

Thanks for the bug report, @wladekb
